package adguard

// adguard_client defaults
const CLIENT_USE_GLOBAL_SETTINGS = true
const CLIENT_FILTERING_ENABLED = false
const CLIENT_PARENTAL_CONTROL_ENABLED = false
const CLIENT_SAFEBROWSING_ENABLED = false
const CLIENT_SAFE_SEARCH_ENABLED = false
const CLIENT_USE_GLOBAL_BLOCKED_SERVICES = true
const CLIENT_IGNORE_QUERYLOG = false
const CLIENT_IGNORE_STATISTICS = false
const CLIENT_UPSTREAMS_CACHE_ENABLED = false
const CLIENT_UPSTREAMS_CACHE_SIZE = 0
const CLIENT_UPSTREAMS_CACHE_SIZE_MAX = 4294967295
