# Terraform Provider release workflow
name: Release

on:
  push:
    tags:
      - "v*"

# releases need permissions to read and write the repository contents
permissions:
  contents: write

jobs:
  # run acceptance tests
  tests:
    uses: ./.github/workflows/testacc.yaml
  goreleaser:
    # require tests to pass
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # allow goreleaser to access older tag information
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          args: release --clean
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
